spring:
  application:
    name: service-consumer

  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 192.168.99.28:8848
server:
  # 服务端口
  port: 8080

management:
  # 端点检查(健康检查)
  # http://wzpc:8070/actuator/nacos-discovery
  endpoints:
    web:
      exposure:
        include: "*"